config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
  
  # API routes for mobile apps
  namespace :api do
    namespace :v1 do
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end
  end
  
  # Turbo Native path configuration
  get 'turbo/ios_path_configuration', to: 'turbo#ios_path_configuration'
  get 'turbo/android_path_configuration', to: 'turbo#android_path_configuration'

  resources :posts
  resources :families
  resources :milestones
  resources :relationships, except: [:edit, :update]
  resources :timeline, only: [:index]
  get '/timeline/truncated', to: 'timeline#show_truncated'
  resources :users do
    resources :posts, only: [:index]
    resources :milestones, only: [:index, :show]
  end
  resources :families do
    resources :milestones, only: [:index, :show]
  end
  resources :posts do
    resources :milestones, only: [:index, :show]
  end

  get '/login', to: 'users#login_form'
  post '/login', to: 'users#login'
  post '/logout', to: 'users#logout'
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :set_random_password, on: :create, unless: %i[claimed password]
  before_validation :set_random_username, on: :create, unless: %i[claimed username]

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, if: :claimed

  before_save :downcase_username

  has_many :posts
  belongs_to :family, optional: true
  has_and_belongs_to_many :tagged_posts, class_name: 'Post'
  has_many :milestones, as: :milestoneable, dependent: :destroy
  has_many :created_milestones, class_name: 'Milestone', foreign_key: 'created_by_user_id', dependent: :destroy
  
  has_many :relationships, dependent: :destroy
  has_many :inverse_relationships, class_name: 'Relationship', foreign_key: 'related_user_id', dependent: :destroy
  has_many :related_users, through: :relationships, source: :related_user
  has_secure_password

  enum :role, { default: 0, manager: 1, admin: 2 }

  # Token authentication for mobile apps
  before_create :generate_authentication_token

  def name
    "#{first_name} #{last_name}"
  end

  def post_count
    Post.where(user_id: id).count
  end

  def age
    return nil unless birthdate

    ((Date.current - birthdate) / 365.25).floor
  end

  def age_in_months
    return nil unless birthdate

    ((Date.current - birthdate) / 30.44).floor # Average days per month
  end

  def display_age
    return nil unless birthdate

    years = age
    months = age_in_months
    days = (Date.current - birthdate).to_i

    if years >= 1
      "#{years} #{'year'.pluralize(years)} old"
    elsif months >= 1
      "#{months} #{'month'.pluralize(months)} old"
    elsif days >= 1
      "#{days} #{'day'.pluralize(days)} old"
    end
  end

  def family_members
    return User.none unless family

    family.users.where.not(id:)
  end

  def all_related_users
    User.joins("LEFT JOIN relationships ON relationships.related_user_id = users.id")
        .where("relationships.user_id = ? OR users.id IN (?)", id, related_users.pluck(:id))
        .where.not(id: id)
        .distinct
  end

  def related_posts
    Post.joins(:user)
        .where(users: { id: related_users.pluck(:id) })
        .where(private: false)
        .order(created_at: :desc)
  end

  def relationship_with(other_user)
    relationships.find_by(related_user: other_user)
  end

  def relationship_type_with(other_user)
    relationship_with(other_user)&.relationship_type
  end

  # Generate new authentication token
  def regenerate_authentication_token
    self.authentication_token = generate_token
    save
  end

  private

  # https://stackoverflow.com/a/34391252
  def set_random_password
    self.password = random_value
  end

  def set_random_username
    self.username = random_value.downcase
  end

  def random_value
    SecureRandom.base64(100)[0, 72]
  end

  def downcase_username
    self.username = username.downcase if username.present?
  end

  def generate_authentication_token
    self.authentication_token = generate_token
  end

  def generate_token
    loop do
      token = SecureRandom.hex(32)
      break token unless User.exists?(authentication_token: token)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: %i[new create login_form login]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user_action, only: %i[show edit update destroy]
  before_action :require_manager_or_admin, only: %i[index destroy]

  def index
    @users = User.all.order(created_at: :desc)
  end

  def show; end

  def new
    claimed_status = !!params[:claimed]
    @user = User.new(claimed: claimed_status)
  end

  def create
    @user = User.new(user_params)

    return render :new, status: :unprocessable_entity unless @user.save

    if @user.claimed # newly created and claimed/registered user
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
      redirect_to root_path
    else # created, but not claimed user
      redirect_to @user
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def login_form; end

  def login
    user = User.find_by(username: params[:username])

    if user&.authenticate(params[:password])
      # Generate new token if user doesn't have one
      user.regenerate_authentication_token unless user.authentication_token
      
      if turbo_native_app?
        # Return JSON with token for mobile apps
        render json: { 
          token: user.authentication_token,
          user: {
            id: user.id,
            name: user.name,
            username: user.username,
            role: user.role
          }
        }
      else
        # Standard web login
        session[:user_id] = user.id
        flash[:success] = "Welcome, #{user.name}!"
        redirect_to root_path
      end
    else
      if turbo_native_app?
        render json: { error: 'Invalid username or password' }, status: :unauthorized
      else
        flash[:error] = 'Sorry, your username or password did not match what we have on record.'
        render :login_form
      end
    end
  end

  def logout
    session.delete :user_id
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def authorize_user_action
    authorize_user_access(@user)
  end

  def user_params
    permitted_params = %i[first_name last_name middle_name birthdate nickname claimed]

    if params[:user][:claimed]
      permitted_params << :username
      permitted_params << :password
    end

    params.require(:user).permit(permitted_params)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  <div id="user-edit-details">
    <% if @user.claimed %>
      <div>
        <%= form.label :username %><br>
        <%= form.text_field :username %>
        <% @user.errors.full_messages_for(:username).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div>
        <%= form.label :password %><br>
        <%= form.password_field :password %>
        <% @user.errors.full_messages_for(:password).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>

    <div>
      <%= form.label :first_name %><br>
      <%= form.text_field :first_name %>
      <% @user.errors.full_messages_for(:first_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :middle_name %><br>
      <%= form.text_field :middle_name %>
      <% @user.errors.full_messages_for(:middle_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :last_name %><br>
      <%= form.text_field :last_name %>
      <% @user.errors.full_messages_for(:last_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :nickname %><br>
      <%= form.text_field :nickname %>
      <% @user.errors.full_messages_for(:nickname).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :birthdate %><br>
      <%= form.date_field :birthdate %>
      <% @user.errors.full_messages_for(:birthdate).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <%# default the user to unclaimed unless creating a new user who is registered %>
    <%= form.hidden_field :claimed, value: !!params[:claimed] %>

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 id="header-name">Edit <%= @user.name %></h1>
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>All Users</h1>

<%= link_to 'Create User', '/users/new' %>

<ul>
  <% @users.each do |user| %>
    <li id="user-<%= user.id %>">
      <%= link_to user.name, user_path(user.id) %> - <%= user.birthdate %> - <%= user.created_at %> -  <%= link_to "Edit", edit_user_path(user.id) %>
    </li>
  <% end %>
</ul>

app/views/users/login_form.html.erb
<div id="login-form">
  <%= form_with url: login_path, method: :post do |form| %>
    <%= form.label :username, "Username:" %>
    <%= form.text_field :username %>
    <%= form.label :password, "Password:" %>
    <%= form.text_field :password %>
    <%= form.submit "Log In" %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="header">New User</h1>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1 id=header-name><%= @user.name %></h1>
<div id=user-details>
  <p><%= @user.first_name %></p>
  <p><%= @user.middle_name %></p>
  <p><%= @user.last_name %></p>
  <p><%= @user.nickname %></p>
  <p><%= @user.birthdate %></p>
</div>

<div id="post-count">
  <%= link_to "#{@user.post_count} Posts", "/users/#{@user.id}/posts" %>
</div>

<div id="relationships-link">
  <%= link_to "Family Relationships", user_relationships_path(@user), class: "btn btn-outline-primary" %>
</div>

<div>
  <%= link_to 'Edit User', edit_user_path(@user) %>
</div>

<%= link_to 'All Users', users_path %>